image: python:3.11

stages:
  - test
  - deploy

variables:
  PYTHONPYCACHEPREFIX: .cache

test:python:
  stage: test
  script:
    - python -m py_compile server.py
  only:
    - dev

pages:
  stage: deploy
  script:
    - rm -rf public
    - mkdir -p public
    - find . -maxdepth 1 ! -name '.' ! -name 'public' ! -name '.git' ! -name '.gitlab-ci.yml' -exec cp -r {} public/ \;
  artifacts:
    paths:
      - public
  only:
    - dev
