name = "workers-argumentaires"
main = "workers-argumentaires/src/index.ts"
compatibility_date = "2025-09-19"

[observability]
enabled = true

[[kv_namespaces]]
binding = "KV_ARGUMENTAIRES"
id = "6c65d15ef81044c2bbcdf1cafc2e6d7e"

[env.dev]
[[env.dev.kv_namespaces]]
binding = "KV_ARGUMENTAIRES"
id = "e2f3fd64ae59412da14b1a67cf49e217"
